### ISSUE TITLE
Your implementatin needs decoupling

### ISSUE THREAD

**Issue by alibad** [BlueRaja/High-Speed-Priority-Queue-for-C-Sharp#1]
This implementation of the priority queue wouldn't work well with objects in external libraries. It will also stain business objects with data-structure-related methods and properties.

If I want to put an object in this queue, it has to inherit from PriorityQueueNode. This makes any objects I want to put in the queue very tightly coupled with the queue data structure. There is definitely a way to do this and get the same performance without that extreme coupling.

**Comment by BlueRaja** [comment]
> There is definitely a way to do this and get the same performance without that extreme coupling.

No, there isn't.  Have you read [this](https://github.com/BlueRaja/High-Speed-Priority-Queue-for-C-Sharp/wiki/Why-do-I-have-to-extend-FastPriorityQueueNode-to-enqueue-something-to-FastPriorityQueue%3F)?

That being said, I have created an implementation which is safer and easier to use _(safety checks in the release version, thread-safe, enqueues any object)_, but haven't had time to test and release it yet.  I will try to get around to that soon.

**Comment by alibad** [comment]
Ok, that adds some more context. But still...

Let me give you this very simple example. I have an int. Now I have to create an IntWrapper class, make it inherit from your class, take the cost of storing all the 3 extra properties (double, long, long), take in the extra cost of allocation, with the added disadvantage of complexity. Too much overhead for what someone would be looking for in a priority queue.

A priority queue is mainly used to enqueue and dequeue by priority (Min heap or max heap), not to check if the queue contains a certain value. You implementation is not improving performance of expected operations on a priority queue (in fact it's slightly adding a bit perf\memory overhead on those operations). If you want to optimize for lookup, just use a different data structure.

**Comment by BlueRaja** [comment]
A normal priority queue will have the exact same overhead, it will just be hidden from you _(at the cost of a small amount of speed)_.

This priority queue was originally written to be _as fast as humanly possible_ for path-finding applications specifically, so enqueuing primitives wasn't an initial design consideration.  However, as I said above, I've now written a more widely-applicable implementation, I just need to find time to test and publish it.

**Comment by BlueRaja** [comment]
I've pushed what I have so far to the [SafePriorityQueue branch](https://github.com/BlueRaja/High-Speed-Priority-Queue-for-C-Sharp/tree/SafePriorityQueue).  The 'fast' queue has been renamed to `FastPriorityQueue`, while the 'convenient' queue is `SafePriorityQueue`.

Please be aware that some behavior is liable to change _(eg. I'm not sure if I want `First` to return null or throw an exception when the queue is empty; or if duplicate keys should be allowed in `SafePriorityQueue` since they cannot be allowed in `FastPriorityQueue`)_

**Comment by BlueRaja** [comment]
I've completed the implementation and created a PR: #2.  Would you like to test it out before I merge?

**Comment by BlueRaja** [comment]
PR has been merged!  The new implementation is called `SimplePriorityQueue`.  It doesn't have the coupling issues, it automatically resizes, it contains lots of safety checks, and it's thread-safe.

The original priority queue has been renamed to `FastPriorityQueue`.

**Comment by alibad** [comment]
Hi Raja,

Sorry I haven't been able to respond and review. Glad to see the improvements!
