### ISSUE TITLE
PCL support?

### ISSUE THREAD

**Issue by Confuset** [BlueRaja/High-Speed-Priority-Queue-for-C-Sharp#18]
Hello,
I wanted to use the priority queue in a PCL (Portable Class Library).
But it is not working. I tried to create a nuget package but that failed.

It is easy to create a PCL from the code and if I compile it an directly reference the lib it works. But i failed to create a nuget-package..

Cheers

**Comment by BlueRaja** [comment]
I've included support for .Net 2.0, .Net 4.5, and UWP.  Do none of these work for PCL (I really know nothing about PCL)?

**Comment by Confuset** [comment]
Well. the strange thing is that when i build it manually iam able to reference the dll directly even from a PCL.
But installing it fails, because the reference can not be resolve.

the official nuget package fails completly...

**Comment by Confuset** [comment]
Accidently closed it..

**Comment by BlueRaja** [comment]
PCL support for frameworks `net40+sl5+win8+wpa81+wp8` has been added in version 4.0.2.

Please reopen if you continue to have issues.

**Comment by Confuset** [comment]
took a while to get back to this,
but it is working 👍
