### ISSUE TITLE
Doesn't work in dotnetcore [netcoreapp target]

### ISSUE THREAD

**Issue by tomshackell** [BlueRaja/High-Speed-Priority-Queue-for-C-Sharp#22]
Hello,

I was hoping to use this in a project I'm working on. But it seems it doesn't support dotnetcore, which is surprising as I can't see any particular reason the code wouldn't work in .NET Core.

> error: Package OptimizedPriorityQueue 4.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package OptimizedPriorityQueue 4.0.0 supports:
> error:   - net20 (.NETFramework,Version=v2.0)
> error:   - net45 (.NETFramework,Version=v4.5)
> error:   - netcore45 (.NETCore,Version=v4.5)
> error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.

**Comment by BlueRaja** [comment]
I'm planning on fixing this in the near future.

Edit: Er, wait, why is it attempting to add the `net20` dll to the project?  Did you add the project through NuGet, or pull the code directly?

**Comment by tomshackell** [comment]
It's not, it's just listing the platforms that would be supported (net20, net45 or netcore45). This is what "dotnet restore" outputs when using dotnet core. 

I believe adding support for the platform netstandard11 or greater should do it since that is supported by both .NET Core and .NET Framework 4.5

https://docs.microsoft.com/en-us/dotnet/articles/standard/library

**Comment by BlueRaja** [comment]
Ok - sorry, never worked with .Net Core before

But yes, I plan to support .Net Standard 1.0 soon.

**Comment by BlueRaja** [comment]
.Net Standard support has been added in version 4.0.1.  Please reopen if you have any more issues.
