### ISSUE TITLE
Runtime failure when NuGet package is installed in UWP App

### ISSUE THREAD

**Issue by ShawnCowles** [BlueRaja/High-Speed-Priority-Queue-for-C-Sharp#24]
The NuGet package installs without issue when running the app, however, the following exception is thrown: `Could not load file or assembly 'Priority Queue UWP, Version=4.0.3.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`

Looking in the output directly there is a "Priority Queue.dll", which matches the contents of the package.

I think the fault is in the nuspec file, line 26: `<file src="..\Priority Queue UWP\bin\Release\netcore45\Priority Queue UWP.dll" target="lib\netstandard1.0\Priority Queue.dll" />`

The src matches the name of the assembly that is being looked for. Unfortunately, I'm not exactly sure what root cause is.

**Comment by ShawnCowles** [comment]
This looks similar to issue #20

**Comment by BlueRaja** [comment]
Published, sorry it took so long.  Please reopen if the problem persists.
