### ISSUE TITLE
Retrieve priority in Peek/Dequeue

### ISSUE THREAD

**Issue by mat-pielat** [BlueRaja/High-Speed-Priority-Queue-for-C-Sharp#27]
Sometimes the priority is a part of information. It would be nice to have overloaded First element lookup and Dequeue which let the user to retrieve it.

**Comment by BlueRaja** [comment]
In `FastPriorityQueue`, `Priority` is a property of the `Node`

In `SimplePriorityQueue`, you're correct that there is currently no way to do this.  Good suggestion :+1:

**Comment by mat-pielat** [comment]
Sorry, I've only just downloaded your library via nuget and without looking at `FastPriorityQueue` assumed they have the same abstraction. You could add `Priority` to `SimplePriorityQueue`'s nodes if that makes it any easier.

**Comment by BlueRaja** [comment]
Completed in v4.1.1
`SimplePriorityQueue` now has a `GetPriority(TItem)` method
