### ISSUE TITLE
Unity setup instructions

### ISSUE THREAD

**Issue by EthanVanderHorn** [BlueRaja/High-Speed-Priority-Queue-for-C-Sharp#37]
It would be nice if there were instructions for how to add this project to a Unity project. NuGet doesn't appear to be supported.

**Comment by EthanVanderHorn** [comment]
I managed to get it working by deleting all the folders except "Priority Queue Unity Full" and "Priority Queue" and then dragging the files from "Priority Queue Unity Full" into "Priority Queue" and replacing the existing files. I also had to delete ".Task" from "System.Thread.Task" in several places.

Not sure if this is right but it worked for me.

**Comment by BlueRaja** [comment]
It's possible to get NuGet working with Unity, but that is outside the scope of this project.  There are other sites for explaining how to do that.
