### ISSUE TITLE
FastPriorityQueueNode shouldn't be a class

### ISSUE THREAD

**Issue by hpkruger** [BlueRaja/High-Speed-Priority-Queue-for-C-Sharp#38]
Hi, is there any specific reason why FastPriorityQueueNode.cs is a class and not an interface? Should be something like IFastPriorityQueueable

**Comment by BlueRaja** [comment]
See https://github.com/BlueRaja/High-Speed-Priority-Queue-for-C-Sharp/wiki/Why-do-I-have-to-extend-FastPriorityQueueNode-to-enqueue-something-to-FastPriorityQueue%3F
