### ISSUE TITLE
Universal Windows Platform Compatible

### ISSUE THREAD

**Issue by rockthethird** [BlueRaja/High-Speed-Priority-Queue-for-C-Sharp#4]
@BlueRaja is it much effort to make you NuGet package compatible with the UWP?  I have considered forking your source and taking what I need to make my project work but I figured that might be duplicate effort if this might have already been on your horizon.  Just thought I would ask, thanks for your   ##time!

In Christ,
Rock

**Comment by BlueRaja** [comment]
Is it currently not compatible?  I'm not aware of any API changes to anything that this project uses.

**Comment by rockthethird** [comment]
@BlueRaja,
As a side not I have your code running just fine under a UWP project without modification.  The only work required was to create the new project and move the source to a Shared folder so that both projects can access the files intuitively.  You can observe my changes here: [rockthethird/High-Speed-Priority-Queue-for-C-Sharp](https://github.com/rockthethird/High-Speed-Priority-Queue-for-C-Sharp).

I have no experience with NuGet submissions so I don't want to imply that the required changes would be trivial. My intention is to simply inform you that you have done well in making the code itself compatible with many .NET versions.  And that just maybe the community can benefit from the future proofing of your repository.

**Comment by rockthethird** [comment]
@BlueRaja,
To answer your question directly, the package is currently not installable through NuGet.  As for its compatibility, I believe the code would work as is.  My opinion stems from my previous comment which states the fact that my only change required was the need for adding the source files to specifically to a UWP project.

(Sorry my reply was already typed out before and sent before I fully understood you comment).

**Comment by BlueRaja** [comment]
I have no idea how to make this library compatible with UWP, there's absolutely no reason it wouldn't be already.  I tried playing with it for a few hours today but didn't get anywhere.

I've asked [this question](http://stackoverflow.com/questions/36670422/how-do-i-make-an-existing-c-sharp-library-uwp-compatible) on StackOverflow for help, but it doesn't seem to be getting much attention.  I'll put a bounty on it in a few days to see if that helps.

**Comment by rockthethird** [comment]
Thanks for giving so much attention to the matter. I should have time to
look into this next week and will provide my findings.

In Christ,
Rock

**Comment by BlueRaja** [comment]
I put a 200 rep bounty on it, but it didn't draw any extra attention :( Any luck on your end?

**Comment by rockthethird** [comment]
Sorry I have been so swamped with work.  I will hopefully be able to check things out soon.

**Comment by rockthethird** [comment]
After looking into your posting a little more it appears that you must add another project that targets the UWP.  After that the NuGet packaging magic should just work as described by a couple commenters.  If it is any consolation your code seems to be fully UWP compatible and require no modification.  From my ability to simply import your code to a UWP, for maintainability my suggestion would be to link all source files to the new UWP project in your solution rather than allowing the Add->Existing Item dialog to copy the files.

In Christ,
Rock

**Comment by BlueRaja** [comment]
Completed in #13
