### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by HurricanKai** [BlueRaja/High-Speed-Priority-Queue-for-C-Sharp#41]
Just a little Typo in the Description of GenericPriorityQueue,
`/// <typeparam name="TItem">The values in the queue.  Must extend the GenericPriorityQueue class</typeparam>`
It shoud be 
`/// <typeparam name="TItem">The values in the queue.  Must extend the GenericPriorityQueueNode class</typeparam>`

Thanks for the Great Work!

**Comment by BlueRaja** [comment]
Fixed in v4.2.0
