### ISSUE TITLE
NUnit tests do not run in debug in Visual Studio 2019

### ISSUE THREAD

**Issue by Nejat** [BlueRaja/High-Speed-Priority-Queue-for-C-Sharp#45]
I had to replace the existing NUnit nuget package with the NUnitTestAdapter.WithFramework buget package to run the tests in the Debug configuration

as described in the following Visual Studio Develop Community thread

https://developercommunity.visualstudio.com/content/problem/527276/nunit-2-unit-tests-not-running-in-vs-2019.html

the test do run in the Release configuration with the existing package.

**Comment by BlueRaja** [comment]
I'm able to run the unit tests in debug and release just fine in VS 2019.

However, it's easy to add `NUnitTestAdapter.WithFramework`, so I've done that in v5.0.0.  Hopefully this fixes the issue for you.
