### ISSUE TITLE
Documentation contradicts examples

### ISSUE THREAD

**Issue by WazWaz** [BlueRaja/High-Speed-Priority-Queue-for-C-Sharp#47]
It appears that the documentation of FastPriorityQueueNode.Priority is from some previous version as it talks about setting the Priority in the constructor of the node, and yet FastPriorityQueue.Enqueue now has the priority as a parameter, so it seems wrong for the node to be setting anything, and sure enough, the example doesn't.

Is it the example or the Priority documentation that is misleading?

**Comment by BlueRaja** [comment]
Yep, looks like I missed a documentation update.  Good catch!  I'll fix this in the next minor release _(which may be a while..)_

**Comment by BlueRaja** [comment]
Fixed in v5.0.0
