### ISSUE TITLE
Assembly name has a space in it.

### ISSUE THREAD

**Issue by akanakia** [BlueRaja/High-Speed-Priority-Queue-for-C-Sharp#48]
The name of dll assembly "Priority Queue.dll" causes issues on systems that do not allow spaces in file names. I would like to use this project in my work but cannot due to this limitation. I request that you update the nuget package to change the assembly name to PriorityQueue.dll or similar (without a space) to overcome this. Thank you.

**Comment by GF-Huang** [comment]
Agree, it's a bad idea that a space inside dll name.

**Comment by BlueRaja** [comment]
Fixed in v5.0.0
