### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by Zerglrisk** [BlueRaja/High-Speed-Priority-Queue-for-C-Sharp#5]
if node has same prioirty, enqueue has keep seq by inser timing? can you show the prove?

**Comment by BlueRaja** [comment]
Yes, as mentioned on the front page, this is a stable priority queue.  It uses the [InsertionIndex](https://github.com/BlueRaja/High-Speed-Priority-Queue-for-C-Sharp/blob/master/Priority%20Queue/FastPriorityQueueNode.cs#L14) to achieve this.

**Comment by BlueRaja** [comment]
It should be mentioned that after #7, `FastPriorityQueue` is no longer stable.  If you _need_ a stable implemention, I've provided `StablePriorityQueue` which is the same thing but stable (and about 2% slower)
