### ISSUE TITLE
Add strong name to this NuGet

### ISSUE THREAD

**Issue by maxkoshevoi** [BlueRaja/High-Speed-Priority-Queue-for-C-Sharp#53]
Could you please add string name to this assembly? I cannot reference it in my project that is strongly named.

First I get this warning on compile time:
```
CS8002	Referenced assembly 'Priority Queue, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```

And than this error on runtime:
```
System.IO.FileLoadException: Could not load file or assembly 'Priority Queue, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
```

**Comment by toeb** [comment]
I am having the same issue.  
I will be trying this https://stackoverflow.com/questions/1220519/how-to-sign-a-net-assembly-dll-file-with-a-strong-name in the mean time

**Comment by BlueRaja** [comment]
The assemblies are now Strong Name signed in 5.1.0.

I've included the private keys in the repo, [as recommended by Microsoft](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named#why-strong-name-your-assemblies). This comes as a surprise to many people, but Strong Names are not a security feature.
